Vagrant.configure("2") do |config|

   config.vm.network "forwarded_port", guest: 8080, host: 8888
   config.vm.network "forwarded_port", guest: 80, host: 5050
   config.vm.network "forwarded_port", guest: 3306, host: 33306

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     sudo apt install git -y
     sudo apt install tomcat9 -y
     sudo apt install openjdk-8-jdk-headless -y
     git clone https://github.com/kimhaengun/Bit-web.git
     rm -rf /var/lib/tomcat9/webapps/ROOT
     mv Bit-web/ www/
     cd www
     cd day56
     sudo apt install maven -y
     mvn package
     sudo mv /home/vagrant/www/day56/target/ROOT.war  /var/lib/tomcat9/webapps/ROOT.war
     curl http://localhost:8080
     sudo apt install mysql-server-8.0 -y
     sudo ufw allow 33306/tcp
     sudo systemctl restart ufw
     sudo mysql -u root < create.sql

  SHELL
end
